#!/bin/bash
STATUS="$(VBoxManage list runningvms)"
if [ -n "$STATUS" ]; then

    if [[ $STATUS == *"homestead-7"* ]]
    then
      STATUS='Homestead php7'
    else
      STATUS='Homestead php5.6'
    fi

    MENU="Choose one of the following options:\n\nCurrently running:$STATUS\n"
    dialog --title 'Currently running:' --msgbox "$STATUS" 5 20

    else
    MENU="Choose one of the following options:"
fi

HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=5
BACKTITLE="Vagrant homestead box controller"
TITLE="Choose a box to start"

OPTIONS=(1 "Homestead with php5.6"
         2 "Homestead with php7"
         3 "SSH into php5.6 box"
         4 "SSH into php7 box"
         5 "Quit")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            homestead up
			notify-send "Homestead php5.6 is up. Attempting to ssh into it."
			homestead ssh
            ;;
        2)
            cd /home/YOURFOLDER/Homestead
            vagrant up
            notify-send "Homestead php7 is up. Attempting to ssh into it."
            vagrant ssh
            ;;
        3)
			homestead ssh
            ;;
        4)
            cd /home/YOURFOLDER/Homestead
            vagrant ssh
            ;;
        5)
            echo "Quiting"
            ;;
esac